version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - ./data/redis:/data


